apiVersion: v1
kind: Service
metadata:
  name: {{ include "python.fullname" . }}
  labels:
    {{- include "python.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      port: {{ .Values.service.nodePort }}
  selector:
    {{- include "python.selectorLabels" . | nindent 4 }}
